version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
shallow_clone: true

build:
  verbosity: minimal

install:
  - cinst unity --version 2017.4.1

before_build:
  - dotnet restore
